server:
  port: 8011

spring:
  security:
    oauth2:
      client:
        registration:
          example-spring-authorization-server:
            client-id: example-spring-security-oauth2-jwt-1
            client-name: example-spring-security-oauth2-jwt-1
            client-secret: example-spring-security-oauth2-jwt-1-secret
