server:
  port: 8021

spring:
  security:
    oauth2:
      client:
        registration:
          example-spring-authorization-server:
            client-id: example-spring-security-oauth2-jwt-2
            client-name: example-spring-security-oauth2-jwt-2
            client-secret: example-spring-security-oauth2-jwt-2-secret
